{{- if and .Values.cloudflare.apiToken.createSecret (not .Values.cloudflare.apiToken.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudflare.apiToken.secretName }}
  labels:
    {{- include "routeflare.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.cloudflare.apiToken.secretKey }}: {{ required "cloudflare.apiToken.value is required when creating a secret" .Values.cloudflare.apiToken.value | b64enc }}
{{- end }}

